'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'es' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Definición de las traducciones compartidas del sistemaconst translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.nosotros': 'NOSOTROS',
    'nav.soluciones': 'SOLUCIONES',
    'nav.productos': 'PRODUCTOS',
    'nav.servicios': 'SERVICIOS',
    'nav.plantas': 'PLANTAS',
    'nav.contacto': 'CONTACTO',
    'nav.cotizar': 'Cotizar Ahora',

    // Hero
    'hero.prelabel': 'LÍDERES EN CONCRETO PREMEZCLADO (MIXER) EN LIMA Y PERÚ',
    'hero.title1': 'Concreto premezclado (mixer) en Lima y todo el Perú',
    'hero.title2': 'Dosificación y alta resistencia para su obra',
    'hero.bg_decor': 'QUE TRASCIENDEN.',
    'hero.desc': 'Servicio y venta de concreto premezclado (mixer) en Lima y todo el Perú. Mezclas dosificadas electrónicamente, bombeo de precisión y despacho rápido para construcción.',
    'hero.hook': 'INSPECCIÓN Y COTIZACIÓN 100% GRATIS',
    'hero.cta.cotizar': 'COTIZAR PROYECTO',
    'hero.cta.servicios': 'NUESTROS SERVICIOS',
    'hero.scroll': 'SCROLL',

    // Hero stats
    'hero.stats.despacho.unit': 'm³/mes',
    'hero.stats.despacho.label': 'DESPACHO',
    'hero.stats.trayectoria.unit': 'años',
    'hero.stats.trayectoria.label': 'TRAYECTORIA',
    'hero.stats.plantas.unit': 'plantas',
    'hero.stats.plantas.label': 'EN LIMA',
    'hero.stats.entrega.unit': 'min',
    'hero.stats.entrega.label': 'ENTREGA',
    'hero.stats.entrega.disclaimer': '*Sujeto a tráfico vehicular',

    // Manifesto (Nosotros / Quiénes Somos)
    'manifesto.prelabel': '• ACERCA DE LA EMPRESA',
    'manifesto.title': 'Trabajamos con dedicación en cada uno de tus proyectos.',
    'manifesto.desc': 'Impulsamos la evolución del sector constructivo. En Unimaxcorp combinamos rigor técnico y acompañamiento estratégico en todo el ciclo de vida de los proyectos. Transformamos desafíos técnicos en soluciones a medida, asegurando el cumplimiento de normativas de calidad y seguridad.',
    'manifesto.sub': 'Hemos consolidado nuestra presencia en el sector construcción a través de una gestión impecable en el suministro de concreto premezclado y soluciones de bombeo, garantizando que cada metro cúbico llegue con la precisión que las normas internacionales exigen.',
    'manifesto.cta': 'Conocer la empresa',
    'manifesto.badge': 'Concreto conforme a normas técnicas',
    'manifesto.tab.nosotros': 'QUIÉNES SOMOS',
    'manifesto.tab.mision': 'MISIÓN Y VISIÓN',
    'manifesto.tab.valores': 'VALORES CORPORATIVOS',
    'manifesto.mision.title': 'Misión',
    'manifesto.mision.desc': 'Proveer soluciones integrales en concreto premezclado con los más altos estándares de excelencia. Nuestra misión es maximizar la eficiencia en tiempos y costos mediante logística ágil y productos de calidad superior, garantizando procesos seguros y sostenibles.',
    'manifesto.vision.title': 'Visión',
    'manifesto.vision.desc': 'Consolidarse como el referente indiscutible en la producción de concreto premezclado, liderando la evolución del sector mediante innovación técnica constante y calidad garantizada. Buscamos optimizar tiempos de ejecución y garantizar progreso con compromiso ambiental.',
    'manifesto.proposito.title': 'Propósito',
    'manifesto.proposito.desc': 'Ser un aliado estratégico brindando productos que cumplan estándares de calidad y maquinarias en óptimas condiciones, aportando valor humano con asesorías técnicas.',
    'manifesto.valores.v1.title': 'Integridad y Ética',
    'manifesto.valores.v1.desc': 'Operamos bajo un estándar de conducta intachable fundamentado en la lealtad a los principios éticos y la transparencia total.',
    'manifesto.valores.v2.title': 'Seguridad Total',
    'manifesto.valores.v2.desc': 'La prioridad absoluta es la preservación de la integridad física y mental de todo nuestro personal mediante la prevención.',
    'manifesto.valores.v3.title': 'Asesoramiento',
    'manifesto.valores.v3.desc': 'Acompañamiento estratégico constante con rigor técnico y soporte técnico personalizado directo en obra.',
    'manifesto.valores.v4.title': 'Estándar de Calidad',
    'manifesto.valores.v4.desc': 'Aplicamos pensamiento disruptivo en laboratorio para entregar resultados superiores que redefinen la industria.',
    'manifesto.valores.v5.title': 'Compromiso Real',
    'manifesto.valores.v5.desc': 'Ejercemos la labor con sentido de pertenencia, asumiendo la autoría plena de cada paso y resultado obtenido.',
    'manifesto.valores.v6.title': 'Eco-responsabilidad',
    'manifesto.valores.v6.desc': 'Comprometidos con una gestión ambiental responsable, prácticas sostenibles y procesos de mezclado limpios.',

    // Bento
    'bento.prelabel': '• NUESTRAS SOLUCIONES',
    'bento.title': 'Todo lo que tu proyecto necesita, en un solo aliado.',
    'bento.p1.tag': 'PRODUCTOS',
    'bento.p1.title': 'Concreto Premezclado',
    'bento.p1.item1': "Diseño de mezcla f'c (kg/cm²)",
    'bento.p1.item2': 'Control de calidad en laboratorio',
    'bento.p1.item3': 'Soporte técnico en vaciado',
    'bento.p1.item4': 'Concretos de alta resistencia (HPC)',
    'bento.p1.link': 'Ver Ficha Técnica',
    'bento.p2.tag': 'TECNOLOGÍA',
    'bento.p2.title': 'Logística Inteligente',
    'bento.p2.item1': 'Seguimiento operativo de ruta',
    'bento.p2.item2': 'Control técnico y ensayos normativos',
    'bento.p2.item3': 'Soporte técnico especializado',
    'bento.p2.item4': 'Programación de vaciados continuos',
    'bento.p2.link': 'Ver servicios',
    'bento.p3.tag': 'SERVICIOS',
    'bento.p3.title': 'Bombeo y Maquinaria',
    'bento.p3.item1': 'Bomba pluma: alcance telescópico',
    'bento.p3.item2': 'Bomba estacionaria de alta presión',
    'bento.p3.item3': 'Alquiler de maquinaria pesada',
    'bento.p3.item4': 'Operadores capacitados y certificados',
    'bento.p3.link': 'Ver maquinaria',
    'bento.p4.desc': 'Nuestras plantas dosificadoras en operación',
    'bento.p4.badge': 'DESPACHO CONTINUO 24/7',

    // Process
    'process.prelabel': '• NUESTRO PROCESO',
    'process.title': 'Despachos desde hasta 90 minutos*, según ubicación, tráfico, disponibilidad operativa y condiciones de acceso a obra.',
    'process.s1.title': 'Solicitud',
    'process.s1.desc': 'Formulario o llamada, confirmación en 10 min',
    'process.s2.title': 'Diseño',
    'process.s2.desc': 'Laboratorio valida mezcla según especificaciones',
    'process.s3.title': 'Despacho',
    'process.s3.desc': 'Coordinación directa con operadores y comunicación durante el despacho',
    'process.s4.title': 'Vaciado',
    'process.s4.desc': 'Operador y bomba en sitio, soporte técnico incluido',

    // Fleet
    'fleet.prelabel': '• NUESTRA FLOTA',
    'fleet.title': 'Equipos de última generación para cualquier escala.',
    'fleet.swipe': 'Desliza para explorar',
    'fleet.cta': 'Solicitar',
    'fleet.more.title': 'Ver flota completa',
    'fleet.more.desc': 'Más de 80 equipos disponibles para tu proyecto en Lima y provincias',
    'fleet.more.cta': 'Cotizar Ahora',

    // Testimonial
    'testimonial.prelabel': '• CLIENTES SATISFECHOS',
    'testimonial.title': 'La voz de los que construyen el país.',
    'testimonial.role1': 'Director de Obras · Inmobiliaria Líder',
    'testimonial.role2': 'Gerente de Proyectos · Consorcio Vial Sur',
    'testimonial.role3': 'Ingeniero Residente · Edifica Perú',

    // Projects
    'projects.prelabel': '• PROYECTOS DESTACADOS',
    'projects.title': 'Obras que construyen confianza.',
    'projects.desc': '25 proyectos de gran envergadura y más de 100 obras de menor escala ejecutadas en Lima y provincias, con respaldo técnico y control de calidad en cada entrega.',

    // Certifications
    'cert.prelabel': '• CUMPLIMIENTO NORMATIVO',
    'cert.title': 'Trabajamos conforme a criterios técnicos aplicables al concreto en obra, incluyendo la Norma E.060 y documentación técnica según corresponda.',
    'cert.c1.title': 'Concreto premezclado',
    'cert.c1.desc': 'Suministro y control de mezcla conforme a especificaciones técnicas, la Norma E.060, NTP 339.114 y ASTM C 94.',
    'cert.c2.title': 'Ensayos del concreto fresco y endurecido',
    'cert.c2.desc': 'Ensayos de resistencia en compresión de testigos cilíndricos muestreados en planta, siguiendo los procedimientos ASTM C 172, NTP 339.026, NTP 339.033 y ASTM C-31.',
    'cert.c3.title': 'Materiales y desempeño',
    'cert.c3.desc': 'Control de agregados (Cantera Vielsa, ASTM C33), cemento Holcim Tipo I (ASTM C1150) y aditivos (ASTM 494), con diseño de mezcla bajo norma ACI 211 y la Norma E.060.',

    // Coverage
    'coverage.prelabel': '• NUESTRA COBERTURA',
    'coverage.title': 'Abastecimiento estratégico en Lima Metropolitana.',
    'coverage.desc': 'Operamos con 2 plantas dosificadoras estratégicamente ubicadas para asegurar el tiempo de entrega y la consistencia del concreto en tu obra.',
    'coverage.p1.title': 'Planta Norte (Puente Piedra)',
    'coverage.p1.desc': 'Abastecimiento para Lima Norte y proyectos viales.',
    'coverage.p2.title': 'Planta Centro (Cercado)',
    'coverage.p2.desc': 'Atención rápida a proyectos residenciales y comerciales del centro.',
    'coverage.p3.title': 'Planta Este (Huachipa)',
    'coverage.p3.desc': 'Soporte de alta capacidad para Lima Este y Chosica.',
    'coverage.p4.title': 'Planta Sur (Lurín)',
    'coverage.p4.desc': 'Abastecimiento industrial y mega proyectos del sur.',

    // Contact
    'contact.prelabel': '• COTIZACIÓN INMEDIATA',
    'contact.title': '¿Listo para iniciar tu proyecto?',
    'contact.desc': 'Completa el formulario y un asesor técnico se comunicará contigo en menos de 10 minutos para brindarte una propuesta personalizada.',
    'contact.info.title': 'Atención Inmediata',
    'contact.info.address.title': 'Oficina Principal',
    'contact.info.address.desc': 'Calle Carrozable Lote 4, Lurigancho, Lima',
    'contact.info.phone.title': 'Celular / WhatsApp',
    'contact.info.phone.desc': '+51 932 095 130',
    'contact.info.email.title': 'Correo Técnico',
    'contact.info.email.desc': 'area.comercial@unimaxcorp.com',
    'contact.form.name': 'Nombre y Apellidos',
    'contact.form.phone': 'Teléfono / WhatsApp',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.location': 'Distrito de la Obra',
    'contact.form.service': 'Servicio requerido',
    'contact.form.service.placeholder': 'Seleccione un servicio',
    'contact.form.service.opt1': 'Concreto Premezclado',
    'contact.form.service.opt2': 'Alquiler de Bomba y Maquinaria',
    'contact.form.service.opt3': 'Diseño de Mezcla / Laboratorio',
    'contact.form.volume': 'Volumen Estimado (m³)',
    'contact.form.msg': 'Detalles del Proyecto',
    'contact.form.submit': 'Enviar Solicitud de Cotización',

    // Footer
    'footer.slogan': 'Soluciones integrales de concreto premezclado y maquinaria pesada para la construcción en todo el Perú.',
    'footer.rights': '© 2026 UNIMAX Corp. Todos los derechos reservados.',
    'footer.privacy': 'Políticas de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.reclamaciones': 'Libro de Reclamaciones',
    'footer.cookies': 'Política de Cookies',
    'cookie.banner.text': 'Utilizamos cookies para optimizar tu experiencia y analizar el tráfico del sitio conforme a nuestras políticas.',
    'cookie.banner.accept': 'Aceptar todas',
    'cookie.banner.decline': 'Rechazar analíticas',
    'cookie.banner.info': 'Configurar',

    // Concreto Premezclado Page
    'concrete.hero.title': 'CONCRETO PREMEZCLADO EN PERÚ Y LIMA (MIXER)',
    'concrete.hero.desc': 'Venta y suministro de concreto premezclado (mixer) de alta resistencia en Lima y todo el Perú. Mezclas certificadas dosificadas electrónicamente con despacho continuo.',
    'concrete.intro.title': 'GESTIÓN IMPECABLE Y SOPORTE TÉCNICO DE ALTO NIVEL',
    'concrete.intro.desc': 'En Unimaxcorp, garantizamos que cada metro cúbico llegue a su destino con la precisión y calidad exigidas por las normas internacionales, apoyándonos en una moderna flota y laboratorios avanzados.',
    'concrete.commitment.title': 'MÁS DE 10 AÑOS DE EXPERIENCIA ACUMULADA.',
    'concrete.commitment.desc1': 'En Unimaxcorp, hemos consolidado nuestra presencia en el sector construcción a través de una trayectoria operativa de más de 10 años de experiencia acumulada.',
    'concrete.commitment.desc2': 'Nuestra experiencia se traduce en eficiencia operativa y soporte técnico de alto nivel. Garantizamos que cada metro cúbico llegue a su destino con la precisión y calidad que las normas internacionales exigen.',
    'concrete.commitment.metric1.val': '16.6K',
    'concrete.commitment.metric1.label': 'M3 Entregados',
    'concrete.commitment.metric2.val': '351+',
    'concrete.commitment.metric2.label': 'Obras Locales',
    'concrete.commitment.metric3.val': '97%',
    'concrete.commitment.metric3.label': 'Clientes Conformes',
    'concrete.commitment.quote': '«No solo entregamos material; garantizamos que cada metro cúbico llegue a su destino con la precisión y calidad que las normas internacionales exigen.»',
    'concrete.versatility.title': 'VERSATILIDAD Y ESPECIFICACIONES TÉCNICAS',
    'concrete.versatility.subtitle': 'RESISTENCIA Y PRECISIÓN ESTRUCTURAL.',
    'concrete.versatility.desc': 'Contamos con una amplia gama de diseños de mezcla formulados bajo los más altos estándares de calidad. Nuestra variedad permite cubrir desde elementos no estructurales hasta proyectos de alta exigencia ingenieril.',
    'concrete.versatility.dosificacion.title': 'Dosificación Controlada',
    'concrete.versatility.dosificacion.desc': 'Eliminamos las variaciones técnicas de las mezclas manuales mediante sistemas automatizados que controlan estrictamente las proporciones de cemento, agregados y aditivos.',
    'concrete.applications.banner': 'SOLUCIONES PARA CADA ETAPA DE SU PROYECTO',
    'concrete.accel.title': 'Concreto de Resistencia Acelerada',
    'concrete.accel.subtitle': 'Diseñado para acelerar los tiempos de ejecución y optimizar la rotación de encofrados.',
    'concrete.accel.item3': 'Acelerado a 3 días',
    'concrete.accel.item7': 'Acelerado a 7 días',
    'concrete.accel.item14': 'Acelerado a 14 días',
    'concrete.accel.desc3': 'Ideal para reparaciones urgentes y máxima rotación de encofrados en elementos verticales y placas.',
    'concrete.accel.desc7': 'El estándar residencial que ofrece un balance perfecto entre velocidad y trabajabilidad en techos y vigas.',
    'concrete.accel.desc14': 'Solución robusta para elementos estructurales convencionales con ganancia de resistencia controlada.',
    'concrete.aditivos.title': 'Aditivos Plastificantes',
    'concrete.aditivos.desc': 'Trabajabilidad superior y cohesión de mezcla garantizada sin debilitar la estructura por exceso de agua.',
    'concrete.aditivos.colocacion.title': 'Fácil Colocación',
    'concrete.aditivos.colocacion.desc': 'Ideal para alta densidad de acero, fluye sin disgregarse.',
    'concrete.aditivos.bombeo.title': 'Bombeo Optimizado',
    'concrete.aditivos.bombeo.desc': 'Reduce la fricción en tuberías para un vaciado continuo sin atascos.',
    'concrete.aditivos.cara.title': 'Acabados Cara Vista',
    'concrete.aditivos.cara.desc': 'Superficies lisas, densas y sin imperfecciones o burbujas.',
    'concrete.aditivos.durabilidad.title': 'Durabilidad Final',
    'concrete.aditivos.durabilidad.desc': 'Relación agua-cemento estrictamente garantizada para evitar cangrejeras.',
    'concrete.agregados.title': 'Selección del Tamaño de Agregado',
    'concrete.agregados.desc': 'La correcta elección del tamaño de la piedra es determinante para la eficiencia del vaciado y la integridad estructural.',
    'concrete.agregados.size1.title': 'Piedra 3/8" (Confitillo)',
    'concrete.agregados.size1.desc': 'Ideal para secciones delgadas o alta concentración de acero. Su gran fluidez evita la formación de «cangrejeras» en columnas y placas esbeltas.',
    'concrete.agregados.size2.title': 'Piedra de 1/2"',
    'concrete.agregados.size2.desc': 'El estándar en viviendas y edificaciones convencionales. Ofrece equilibrio óptimo entre resistencia y trabajabilidad en techos y vigas.',
    'concrete.agregados.size3.title': 'Piedra de 3/4"',
    'concrete.agregados.size3.desc': 'Agregado grueso idóneo para vaciados masivos, losas de gran espesor, zapatas gigantes y pavimentos rígidos. Optimiza el cemento y eleva la estabilidad.',
    'concrete.aplicaciones.title': 'Aplicaciones del Concreto Premezclado',
    'concrete.aplicaciones.cimentacion.title': 'Cimentación',
    'concrete.aplicaciones.cimentacion.desc': 'Zapatas, cimientos y muros de contención sólidos.',
    'concrete.aplicaciones.estructuras.title': 'Estructuras Elevadas',
    'concrete.aplicaciones.estructuras.desc': 'Columnas robustas y vigas peraltadas sometidas a grandes cargas.',
    'concrete.aplicaciones.losas.title': 'Losas y Techos',
    'concrete.aplicaciones.losas.desc': 'Losas aligeradas, macizas y techos de cualquier envergadura.',
    'concrete.aplicaciones.pavimentos.title': 'Pavimentos',
    'concrete.aplicaciones.pavimentos.desc': 'Pistas transitadas, veredas urbanas y pisos industriales.',
    'concrete.cta.title': 'Solicite una cotización técnica personalizada para su obra',
    'concrete.cta.desc': 'Solicita una propuesta personalizada para el suministro de concreto premezclado de acuerdo con las especificaciones de tu proyecto.',
    'concrete.cta.whatsapp': 'HABLA CON UN ASESOR',
    'concrete.cta.brochure': 'DESCARGAR BROCHURE',

    // Bomba de Concreto Page
    'pump.hero.title': 'BOMBEO DE CONCRETO Y MAQUINARIAS',
    'pump.hero.desc': 'Servicio de bombeo de concreto en Lima y provincias. Alquiler de bombas telescópicas y estacionarias de alta presión para su obra.',
    'pump.intro.title': 'SOLUCIONES DE BOMBEO Y MAQUINARIA PESADA',
    'pump.intro.desc': 'Equipamiento moderno y operadores certificados que garantizan la colocación exacta del concreto en el menor tiempo posible, minimizando costos y fatiga operativa.',
    'pump.equipos.title': 'Equipamientos a su Medida',
    'pump.equipos.estacionaria.title': 'Bomba Estacionaria',
    'pump.equipos.estacionaria.desc': 'La solución perfecta para «grandes distancias y volúmenes constantes». Se utiliza mediante un sistema de tuberías fijas, siendo excelente para túneles, edificios de gran altura o áreas donde una pluma no puede maniobrar.',
    'pump.equipos.pluma.title': 'Bomba Pluma (Autobomba)',
    'pump.equipos.pluma.desc': 'Ideal para proyectos que requieren rapidez y versatilidad. Gracias a su brazo articulado telescópico, permite colocar el concreto en alturas elevadas o lugares de difícil acceso sin necesidad de tubería estática adicional.',
    'pump.ventajas.title': 'Eficiencia y Optimización Operativa',
    'pump.ventajas.desc': 'Invertir en el servicio de bombeo de Unimaxcorp no es un gasto, es una estrategia de optimización financiera para su construcción.',
    'pump.ventajas.tiempo.title': 'Ahorro de Tiempo',
    'pump.ventajas.tiempo.desc': 'Reduce los tiempos de vaciado hasta en un 60% en comparación con métodos tradicionales.',
    'pump.ventajas.personal.title': 'Optimización de Personal',
    'pump.ventajas.personal.desc': 'Requiere menos personal para el acarreo, permitiendo que su equipo se enfoque en el acabado y calidad.',
    'pump.ventajas.desperdicio.title': 'Cero Desperdicio',
    'pump.ventajas.desperdicio.desc': 'Colocación precisa del material, eliminando las mermas por transporte manual.',
    'pump.ventajas.quote': '«Nuestra tecnología transforma metros cúbicos en eficiencia financiera.»',
    'pump.cta.title': 'Consulte con nuestros ingenieros especializados cuál es el sistema de bombeo que mejor se adapta a su proyecto',
    'pump.cta.desc': 'Comuníquese con nosotros y le brindaremos asesoramiento técnico sin costo para seleccionar el equipo óptimo para su obra.',
    'pump.cta.whatsapp': 'SOLICITAR COTIZACIÓN',
    'nav.proyectos': 'PROYECTOS',
    'projects.hero.title': 'NUESTROS PROYECTOS',
    'projects.hero.desc': 'Conozca las obras e infraestructuras de éxito donde hemos suministrado concreto premezclado de alta resistencia con precisión y puntualidad.',
    'projects.filter.all': 'TODOS',
    'projects.filter.building': 'EDIFICACIÓN',
    'projects.filter.pavements': 'PAVIMENTOS',
    'projects.filter.pours': 'VACIADOS',
    'projects.filter.infra': 'INFRAESTRUCTURA',
    'projects.cta.title': '¿TIENE UN PROYECTO EN MENTE?',
    'projects.cta.desc': 'Permítanos asesorarle técnicamente sin costo alguno. Suministramos concreto premezclado y bombeo continuo adaptados a las exigencias de su obra.',
    'projects.cta.whatsapp': 'HABLA CON UN ASESOR',
    'projects.cta.quote': 'COTIZAR AHORA',
  },
  en: {
    // Navigation
    'nav.nosotros': 'ABOUT US',
    'nav.soluciones': 'SOLUTIONS',
    'nav.productos': 'PRODUCTS',
    'nav.servicios': 'SERVICES',
    'nav.plantas': 'PLANTS',
    'nav.contacto': 'CONTACT',
    'nav.cotizar': 'Quote Now',

    // Hero
    'hero.prelabel': 'LEADERS IN READY-MIX CONCRETE IN LIMA & PERU',
    'hero.title1': 'Ready-mix concrete in Lima and all Peru',
    'hero.title2': 'Automated batching and high resistance for your project',
    'hero.bg_decor': 'TRANSCEND.',
    'hero.desc': 'Specialists in Ready-Mix Concrete in Lima and Peru. Electronically batched mixes, precision pumping, and fast site dispatch.',
    'hero.hook': 'FREE INSPECTION & QUOTE — 100% FREE',
    'hero.cta.cotizar': 'QUOTE PROJECT',
    'hero.cta.servicios': 'OUR SERVICES',
    'hero.scroll': 'SCROLL',

    // Hero stats
    'hero.stats.despacho.unit': 'm³/mo',
    'hero.stats.despacho.label': 'DISPATCH',
    'hero.stats.trayectoria.unit': 'years',
    'hero.stats.trayectoria.label': 'TRAJECTORY',
    'hero.stats.plantas.unit': 'plants',
    'hero.stats.plantas.label': 'IN LIMA',
    'hero.stats.entrega.unit': 'min',
    'hero.stats.entrega.label': 'DELIVERY',
    'hero.stats.entrega.disclaimer': '*Subject to traffic conditions',

    // Manifesto (Nosotros / Quiénes Somos)
    'manifesto.prelabel': '• ABOUT THE COMPANY',
    'manifesto.title': 'We work with dedication on every single one of your projects.',
    'manifesto.desc': 'We drive the evolution of the construction sector. At Unimaxcorp we combine technical rigor and strategic support throughout the lifecycle of your projects. We transform technical challenges into tailored solutions, ensuring compliance with quality and safety regulations.',
    'manifesto.sub': 'We have consolidated our presence in the construction sector through impeccable management of ready-mix supply and pumping solutions, guaranteeing that every cubic meter arrives with the precision that international standards demand.',
    'manifesto.cta': 'About the company',
    'manifesto.badge': 'Concrete compliant with technical standards',
    'manifesto.tab.nosotros': 'WHO WE ARE',
    'manifesto.tab.mision': 'MISSION & VISION',
    'manifesto.tab.valores': 'CORPORATE VALUES',
    'manifesto.mision.title': 'Mission',
    'manifesto.mision.desc': 'To provide comprehensive ready-mix concrete solutions under the highest standards of excellence. Our mission is to maximize efficiency in time and costs through agile logistics and superior quality products, guaranteeing safe and sustainable processes.',
    'manifesto.vision.title': 'Vision',
    'manifesto.vision.desc': 'To consolidate as the indisputable benchmark in ready-mix concrete production, leading the evolution of the sector through constant technical innovation and guaranteed quality. We seek to optimize execution times and guarantee progress with environmental commitment.',
    'manifesto.proposito.title': 'Purpose',
    'manifesto.proposito.desc': 'To be a strategic ally providing products that comply with quality standards and heavy machinery in optimal conditions, adding human value with technical advisories.',
    'manifesto.valores.v1.title': 'Integrity & Ethics',
    'manifesto.valores.v1.desc': 'We operate under an impeccable standard of conduct based on loyalty and full transparency.',
    'manifesto.valores.v2.title': 'Total Safety',
    'manifesto.valores.v2.desc': 'Our absolute priority is the preservation of the physical and mental integrity of all our personnel through prevention.',
    'manifesto.valores.v3.title': 'Advisory Support',
    'manifesto.valores.v3.desc': 'Constant strategic support with technical rigor and personalized on-site guidance.',
    'manifesto.valores.v4.title': 'Quality Standard',
    'manifesto.valores.v4.desc': 'We apply disruptive thinking in laboratory to deliver superior results that redefine structural standards.',
    'manifesto.valores.v5.title': 'Real Commitment',
    'manifesto.valores.v5.desc': 'We perform our work with ownership, taking full accountability for every single step and result.',
    'manifesto.valores.v6.title': 'Eco-responsibility',
    'manifesto.valores.v6.desc': 'Committed to sustainable practices, responsible environmental management, and clean mixing processes.',

    // Bento
    'bento.prelabel': '• OUR SOLUTIONS',
    'bento.title': 'Everything your project needs, in a single ally.',
    'bento.p1.tag': 'PRODUCTS',
    'bento.p1.title': 'Ready-Mix Concrete',
    'bento.p1.item1': "Concrete mix design f'c (kg/cm²)",
    'bento.p1.item2': 'Quality control in laboratory',
    'bento.p1.item3': 'On-site pouring technical support',
    'bento.p1.item4': 'High Performance Concrete (HPC)',
    'bento.p1.link': 'View Technical Sheet',
    'bento.p2.tag': 'TECHNOLOGY',
    'bento.p2.title': 'Smart Logistics',
    'bento.p2.item1': 'Operational route tracking',
    'bento.p2.item2': 'Technical control and standardized testing',
    'bento.p2.item3': 'Specialized technical support',
    'bento.p2.item4': 'Continuous pouring schedule',
    'bento.p2.link': 'View services',
    'bento.p3.tag': 'SERVICES',
    'bento.p3.title': 'Pumping & Machinery',
    'bento.p3.item1': 'Boom pump: telescopic reach',
    'bento.p3.item2': 'High-pressure stationary pumps',
    'bento.p3.item3': 'Heavy machinery rental',
    'bento.p3.item4': 'Trained and certified operators',
    'bento.p3.link': 'View machinery',
    'bento.p4.desc': 'Our batching plants in operation',
    'bento.p4.badge': 'CONTINUOUS DISPATCH 24/7',

    // Process
    'process.prelabel': '• OUR PROCESS',
    'process.title': 'Dispatches from up to 90 minutes*, subject to location, traffic, operational availability, and site access.',
    'process.s1.title': 'Request',
    'process.s1.desc': 'Form or phone call, confirmation in 10 mins',
    'process.s2.title': 'Design',
    'process.s2.desc': 'Laboratory validates ready-mix as per specs',
    'process.s3.title': 'Dispatch',
    'process.s3.desc': 'Direct coordination with operators and communication during dispatch',
    'process.s4.title': 'Pouring',
    'process.s4.desc': 'Operator and pump on-site, technical support',

    // Fleet
    'fleet.prelabel': '• OUR FLEET',
    'fleet.title': 'State-of-the-art machinery for any scale.',
    'fleet.swipe': 'Swipe to explore',
    'fleet.cta': 'Request',
    'fleet.more.title': 'View entire fleet',
    'fleet.more.desc': 'Over 80 units available for your project in Lima and provinces',
    'fleet.more.cta': 'Quote Now',

    // Testimonial
    'testimonial.prelabel': '• SATISFIED CLIENTS',
    'testimonial.title': 'The voice of those who build the country.',
    'testimonial.role1': 'Construction Director · Inmobiliaria Líder',
    'testimonial.role2': 'Project Manager · Consorcio Vial Sur',
    'testimonial.role3': 'Resident Engineer · Edifica Perú',

    // Projects
    'projects.prelabel': '• FEATURED PROJECTS',
    'projects.title': 'Works that build trust.',
    'projects.desc': '25 large-scale projects and over 100 smaller works completed in Lima and provinces, with technical backing and quality control on every delivery.',

    // Certifications
    'cert.prelabel': '• REGULATORY COMPLIANCE',
    'cert.title': 'We work in accordance with applicable technical criteria for concrete on site, including Standard E.060 and technical documentation as appropriate.',
    'cert.c1.title': 'Ready-mix concrete',
    'cert.c1.desc': 'Supply and mix control in compliance with technical specifications, Standard E.060, NTP 339.114 and ASTM C 94.',
    'cert.c2.title': 'Fresh and hardened concrete testing',
    'cert.c2.desc': 'Compressive strength testing of cylindrical specimens sampled at plant, following ASTM C 172, NTP 339.026, NTP 339.033 and ASTM C-31 procedures.',
    'cert.c3.title': 'Materials and performance',
    'cert.c3.desc': 'Aggregate control (Cantera Vielsa, ASTM C33), Holcim Type I cement (ASTM C1150) and chemical admixtures (ASTM 494), with mix design under ACI 211 and Standard E.060.',

    // Coverage
    'coverage.prelabel': '• OUR COVERAGE',
    'coverage.title': 'Strategic supply across Metropolitan Lima.',
    'coverage.desc': 'We operate with 2 strategically located batching plants to ensure delivery times and ready-mix consistency at your job site.',
    'coverage.p1.title': 'North Plant (Puente Piedra)',
    'coverage.p1.desc': 'Supply for North Lima and roadway infrastructure projects.',
    'coverage.p2.title': 'Central Plant (Cercado)',
    'coverage.p2.desc': 'Fast response to residential and commercial projects in center Lima.',
    'coverage.p3.title': 'East Plant (Huachipa)',
    'coverage.p3.desc': 'High-capacity support for East Lima and Chosica.',
    'coverage.p4.title': 'South Plant (Lurín)',
    'coverage.p4.desc': 'Industrial supply and mega projects in the south.',

    // Contact
    'contact.prelabel': '• IMMEDIATE QUOTE',
    'contact.title': 'Ready to start your project?',
    'contact.desc': 'Fill out the form and a technical advisor will contact you in less than 10 minutes to provide a customized proposal.',
    'contact.info.title': 'Immediate Attention',
    'contact.info.address.title': 'Headquarters',
    'contact.info.address.desc': 'Calle Carrozable Lote 4, Lurigancho, Lima',
    'contact.info.phone.title': 'Mobile / WhatsApp',
    'contact.info.phone.desc': '+51 932 095 130',
    'contact.info.email.title': 'Technical Mail',
    'contact.info.email.desc': 'area.comercial@unimaxcorp.com',
    'contact.form.name': 'Full Name',
    'contact.form.phone': 'Phone / WhatsApp',
    'contact.form.email': 'Email Address',
    'contact.form.location': 'Project Location (District)',
    'contact.form.service': 'Required Service',
    'contact.form.service.placeholder': 'Select a service',
    'contact.form.service.opt1': 'Ready-Mix Concrete',
    'contact.form.service.opt2': 'Pump & Heavy Machinery Rental',
    'contact.form.service.opt3': 'Mix Design / Laboratory Service',
    'contact.form.volume': 'Estimated Volume (m³)',
    'contact.form.msg': 'Project Details',
    'contact.form.submit': 'Send Quote Request',

    // Footer
    'footer.slogan': 'Comprehensive ready-mix concrete and heavy machinery rental solutions for construction projects throughout Peru.',
    'footer.rights': '© 2026 UNIMAX Corp. All rights reserved.',
    'footer.privacy': 'Privacy Policies',
    'footer.terms': 'Terms of Service',
    'footer.reclamaciones': 'Complaints Book',
    'footer.cookies': 'Cookie Policy',
    'cookie.banner.text': 'We use cookies to optimize your experience and analyze site traffic in accordance with our policies.',
    'cookie.banner.accept': 'Accept all',
    'cookie.banner.decline': 'Decline analytics',
    'cookie.banner.info': 'Configure',

    // Ready-Mix Concrete Page
    'concrete.hero.title': 'READY-MIX CONCRETE IN LIMA',
    'concrete.hero.desc': 'Supply of high-strength ready-mix concrete in Lima and all Peru. Certified mixes electronically batched for your project.',
    'concrete.intro.title': 'IMPECCABLE MANAGEMENT & HIGH-LEVEL TECHNICAL SUPPORT',
    'concrete.intro.desc': 'At Unimaxcorp, we ensure that every cubic meter reaches its destination with the precision and quality required by international standards, backed by a modern fleet and advanced laboratory testing.',
    'concrete.commitment.title': 'OVER 10 YEARS OF ACCUMULATED EXPERIENCE.',
    'concrete.commitment.desc1': 'At Unimaxcorp, we have consolidated our presence in the construction sector through an operational track record of over 10 years of accumulated experience.',
    'concrete.commitment.desc2': 'Our experience translates into operational efficiency and high-level technical support. We guarantee that every cubic meter reaches its destination with the precision and quality required by international standards.',
    'concrete.commitment.metric1.val': '16.6K',
    'concrete.commitment.metric1.label': 'M3 Delivered',
    'concrete.commitment.metric2.val': '351+',
    'concrete.commitment.metric2.label': 'Local Works',
    'concrete.commitment.metric3.val': '97%',
    'concrete.commitment.metric3.label': 'Satisfied Clients',
    'concrete.commitment.quote': '"We do not just deliver material; we guarantee that every cubic meter reaches its destination with the precision and quality required by international standards."',
    'concrete.versatility.title': 'VERSATILITY AND TECHNICAL SPECIFICATIONS',
    'concrete.versatility.subtitle': 'STRUCTURAL STRENGTH AND PRECISION.',
    'concrete.versatility.desc': 'We have a wide range of concrete mix designs formulated under the highest quality standards. Our variety covers from non-structural elements to high-demand engineering projects.',
    'concrete.versatility.dosificacion.title': 'Controlled Batching',
    'concrete.versatility.dosificacion.desc': 'We eliminate the technical variations of manual mixing through automated systems that strictly control the proportions of cement, aggregates, and admixtures.',
    'concrete.applications.banner': 'SOLUTIONS FOR EVERY STAGE OF YOUR PROJECT',
    'concrete.accel.title': 'Accelerated Strength Concrete',
    'concrete.accel.subtitle': 'Designed to accelerate execution times and optimize formwork turnaround times.',
    'concrete.accel.item3': '3-Day Accelerated',
    'concrete.accel.item7': '7-Day Accelerated',
    'concrete.accel.item14': '14-Day Accelerated',
    'concrete.accel.desc3': 'Ideal for urgent repairs and maximum formwork turnaround in vertical elements and rapid slabs.',
    'concrete.accel.desc7': 'The residential standard offering a perfect balance between speed and workability in roofs and beams.',
    'concrete.accel.desc14': 'Robust solution for conventional structural elements with controlled strength gain.',
    'concrete.aditivos.title': 'Plasticizing Admixtures',
    'concrete.aditivos.desc': 'Superior workability and guaranteed mix cohesion without weakening the structure due to excess water.',
    'concrete.aditivos.colocacion.title': 'Easy Placement',
    'concrete.aditivos.colocacion.desc': 'Ideal for high density of steel, flows without segregation.',
    'concrete.aditivos.bombeo.title': 'Optimized Pumping',
    'concrete.aditivos.bombeo.desc': 'Reduces pipeline friction for continuous pouring without blockages.',
    'concrete.aditivos.cara.title': 'Fair-Faced Finishes',
    'concrete.aditivos.cara.desc': 'Smooth, dense surfaces with zero imperfections or air voids.',
    'concrete.aditivos.durabilidad.title': 'Final Durability',
    'concrete.aditivos.durabilidad.desc': 'Strictly guaranteed water-cement ratio to prevent voids and honeycombs.',
    'concrete.agregados.title': 'Aggregate Size Selection',
    'concrete.agregados.desc': 'The correct choice of stone size is key for pouring efficiency and structural integrity.',
    'concrete.agregados.size1.title': '3/8" Aggregate (Confitillo)',
    'concrete.agregados.size1.desc': 'Recommended for thin sections or high steel density; its high fluidity prevents voids and honeycombs in columns and slender walls.',
    'concrete.agregados.size2.title': '1/2" Aggregate',
    'concrete.agregados.size2.desc': 'Standard aggregate for residential and general construction; offers a perfect balance between strength and placing workability.',
    'concrete.agregados.size3.title': '3/4" Aggregate',
    'concrete.agregados.size3.desc': 'Coarse aggregate ideal for mass pours, thick foundation slabs, heavy footings, and rigid pavements; optimizes cement and maximizes stability.',
    'concrete.aplicaciones.title': 'Ready-Mix Concrete Applications',
    'concrete.aplicaciones.cimentacion.title': 'Foundations',
    'concrete.aplicaciones.cimentacion.desc': 'Solid footings, continuous foundations, and robust retaining walls.',
    'concrete.aplicaciones.estructuras.title': 'Elevated Structures',
    'concrete.aplicaciones.estructuras.desc': 'Robust columns and deep structural beams subjected to heavy loads.',
    'concrete.aplicaciones.losas.title': 'Slabs and Roofs',
    'concrete.aplicaciones.losas.desc': 'Lightweight and solid concrete slabs and roofs of any scope.',
    'concrete.aplicaciones.pavimentos.title': 'Pavements',
    'concrete.aplicaciones.pavimentos.desc': 'High-traffic roads, urban sidewalks, and heavy industrial floors.',
    'concrete.cta.title': 'Request a custom technical quote for your construction site',
    'concrete.cta.desc': 'Request a personalized proposal for the supply of ready-mix concrete in accordance with your project specifications.',
    'concrete.cta.whatsapp': 'TALK TO AN ADVISOR',
    'concrete.cta.brochure': 'DOWNLOAD BROCHURE',

    // Concrete Pump Page
    'pump.hero.title': 'CONCRETE PUMPING & MACHINERY',
    'pump.hero.desc': 'Concrete pumping services in Lima and surrounding provinces. Boom and line pumps rental with full technical support.',
    'pump.intro.title': 'PUMPING SOLUTIONS & HEAVY MACHINERY',
    'pump.intro.desc': 'Modern equipment and certified operators that guarantee exact concrete placement in the shortest possible time, minimizing costs and operational fatigue.',
    'pump.equipos.title': 'Equipment Tailored to Your Needs',
    'pump.equipos.estacionaria.title': 'Stationary Pump',
    'pump.equipos.estacionaria.desc': 'The perfect solution for "long distances and constant volumes". It uses a fixed pipe system, making it excellent for tunnels, deep basements, or high-rise buildings where a boom pump cannot maneuver.',
    'pump.equipos.pluma.title': 'Boom Pump (Autobomba)',
    'pump.equipos.pluma.desc': 'Ideal for projects requiring speed and versatility. Thanks to its telescopic articulated arm, it places concrete at elevated heights or hard-to-reach locations without the need for additional static piping.',
    'pump.ventajas.title': 'Efficiency & Operational Optimization',
    'pump.ventajas.desc': 'Investing in Unimaxcorp\'s pumping service is not an expense, it is a financial optimization strategy for your construction.',
    'pump.ventajas.tiempo.title': 'Time Savings',
    'pump.ventajas.tiempo.desc': 'Reduces concrete placing times by up to 60% compared to traditional manual hauling methods.',
    'pump.ventajas.personal.title': 'Crew Optimization',
    'pump.ventajas.personal.desc': 'Requires less physical labor, allowing your team to focus on concrete finishing and quality control.',
    'pump.ventajas.desperdicio.title': 'Zero Waste',
    'pump.ventajas.desperdicio.desc': 'Precise material placement, eliminating manual transport waste and accidental spills.',
    'pump.ventajas.quote': '"Our technology transforms cubic meters into financial efficiency."',
    'pump.cta.title': 'Consult with our specialized engineers which pumping system best suits your project',
    'pump.cta.desc': 'Get in touch with us and we will provide free technical advice to select the optimal equipment for your work site.',
    'pump.cta.whatsapp': 'REQUEST A QUOTE',
    'nav.proyectos': 'PROJECTS',
    'projects.hero.title': 'OUR PROJECTS',
    'projects.hero.desc': 'Explore the successful construction and infrastructure works where we have supplied high-strength ready-mix concrete with precision and punctuality.',
    'projects.filter.all': 'ALL',
    'projects.filter.building': 'BUILDING',
    'projects.filter.pavements': 'PAVEMENTS',
    'projects.filter.pours': 'POURS',
    'projects.filter.infra': 'INFRASTRUCTURE',
    'projects.cta.title': 'HAVE A PROJECT IN MIND?',
    'projects.cta.desc': 'Let us provide you with free technical advice. We supply ready-mix concrete and continuous pumping tailored to the demands of your job site.',
    'projects.cta.whatsapp': 'TALK TO AN ADVISOR',
    'projects.cta.quote': 'QUOTE NOW',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('es')

  useEffect(() => {
    const saved = localStorage.getItem('unimax-lang') as Language
    if (saved === 'es' || saved === 'en') {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('unimax-lang', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
